/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hacker-room-new.glb -T 
Files: hacker-room-new.glb [34.62MB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/hacker-room-new-transformed.glb [2.56MB] (93%)
*/

import { useGLTF } from '@react-three/drei';

function renderMeshes(object) {
  if (!object) return null;
  if (object.type === "Mesh" || object.type === "SkinnedMesh") {
    console.log("Rendering mesh:", object.name || object.uuid);
    return <primitive object={object} key={object.uuid} />;
  }
  if (object.children && object.children.length > 0) {
    return object.children.map(child => renderMeshes(child));
  }
  return null;
}

export function HackerRoom(props) {
  const { nodes } = useGLTF('/models/hacker-room.glb');
  if (!nodes) return null;

  return (
    <group {...props} scale={[0.1, 0.1, 0.1]}>
      {Object.values(nodes).map((node) => renderMeshes(node))}
    </group>
  );
}

useGLTF.preload('/models/hacker-room.glb');
export default HackerRoom;